### ISSUE TITLE
Automatically hide notification after a few seconds

### ISSUE THREAD

**Issue by sheharyarn** [avielg/AGPushNote#4]
`AGPushNote` notifications should automatically hide (slide back up) after a couple of seconds, just like native iOS notifications.

Again, awesome project.

**Comment by avielg** [comment]
There is a commented call to NSTimer that does exactly that in the code. All you need to to do is uncomment the line. It is documented in the README. Good luck (:

 Aviel Gross | bit.ly/aviel (http://bit.ly/aviel)

**Comment by sheharyarn** [comment]
Awesome, thanks!

**As a reference for others,** it's `Line 150` of `AGPushNoteView.m`. You need to uncomment the line and change `IAAPushNoteView` to `AGPushNoteView`:

``` objective-c
PUSH_VIEW.closeTimer = [NSTimer scheduledTimerWithTimeInterval:CLOSE_PUSH_SEC target:[AGPushNoteView class] selector:@selector(close) userInfo:nil repeats:NO];
```
